export const ErrorCodeEnum = {
    //Auth Errors
    AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
    AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_USER_NOT_ACTIVE: "AUTH_USER_NOT_ACTIVE",

    AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
    AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
    AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
    AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",

    //Access Errors
    ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",

    //Validation and ressource Errors
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

    //system Error
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;